[package]
name = "rumdl"
version = "0.0.16"
edition = "2021"
description = "A fast Markdown linter written in Rust (Ru(st) MarkDown Linter)"
authors = ["Ruben J. Jongejan <ruben.jongejan@gmail.com>"]
license = "MIT"
repository = "https://github.com/rvben/rumdl"
homepage = "https://github.com/rvben/rumdl"
documentation = "https://github.com/rvben/rumdl/blob/main/docs"
readme = "README.md"
keywords = ["markdown", "linter", "markdown-linter", "static-analysis", "documentation"]
categories = ["command-line-utilities", "development-tools", "text-processing"]
exclude = [".github/", ".gitignore", "*.bak"]

[lib]
name = "rumdl"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rumdl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.10.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.32"
thiserror = "2.0.12"
walkdir = "2.5.0"
colored = "3.0.0"
lazy_static = "1.4.0"
fancy-regex = "0.14.0"
toml = "0.8.20"
glob = "0.3.2"
ignore = "0.4.23"
pyo3 = { version = "0.24.0", features = ["extension-module", "abi3-py37"], optional = true }

[features]
default = ["profiling"]
profiling = []
python = ["pyo3"]

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
tempfile = "3.10.1"
ignore = "0.4.23"
walkdir = "2.5.0"
glob = "0.3.2" 
