name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            compatibility: manylinux2014
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install maturin[zig]

      - name: Build wheel
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            maturin build --release --target ${{ matrix.target }} --compatibility ${{ matrix.compatibility }}
          else
            maturin build --release --target ${{ matrix.target }}
          fi

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          path: target/wheels/*.whl
          name: wheels

  upload:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/tags/*')

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: target/wheels

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine
          python -m twine upload --repository testpypi target/wheels/*.whl 